var greeting = 'Hello,${name}!;';
console.log(greeting);
var num = 2;
var num1 = 3;
console.log(Math.pow(num, num1));
var age = 20;
var myFirend = "Alina";
var inroll = (true);
console.log(age, myFirend, inroll);
var indexOne = "numa";
console.log(indexOne);
indexOne = "amaan";
console.log(indexOne);
indexOne = "airah";
console.log(indexOne);
var num_2 = 6;
console.log(num_2);
num_2 = 20;
console.log(num_2);
num_2 = 15;
console.log(num_2);
var color = true;
console.log(color);
color = false;
console.log(color);
//concatination//
var food = "pizza";
var juice = "boba";
var favColor = "pink";
var num3 = 35;
console.log(food, juice);
var result = food + " " + juice + " " + favColor + " " + num3;
console.log(result);
//template literals//
var A = "i like ".concat(food, ", ").concat(juice, " and my favcolor is ").concat(favColor, " \n my fav number is ").concat(num3);
console.log(A);
